name: Deploy Examples to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
        working-directory: ./example/vite/react
      - name: Build Vite React App
        run: pnpm build
        working-directory: ./example/vite/react
      - name: Upload Vite React Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-react-build
          path: ./example/vite/react/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-react]
    steps:
      - uses: actions/checkout@v4
      - name: Download React Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: vite-react-build
          path: ./public
    #   - name: Copy index.html to public directory
    #     run: cp ./example/index.html ./public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          allow_empty_commit: true